{{- range $idx, $value := .Values.services }}
{{- if $value.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "base.fullname" $ }}-{{ $value.name }}-ingress
  labels:
    {{- include "base.labels" $ | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        {{- range $i, $v := $value.ports }}
        - path: {{ $v.path | default "/" }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "base.fullname" $ }}-{{ $value.name }}
              port:
                name: {{ $v.name }}
        {{- end }}
---
{{- end }}
{{- end }}