{{ if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "base.fullname" . }}-prometheus
spec:
  endpoints:
  {{- range $i, $v := .Values.containers }}
  - interval: 5s
    path: {{ $v.prometheus.path }}
    port: {{ $v.prometheus.port }}
    metricRelabelings:
    - sourceLabels: [__name__]
      targetLabel: __name__
      replacement: {{ $v.prometheus.prefix }}$1
  {{- end }}
  
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace}}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}

{{ end }}